use_frameworks!

platform :ios, '9.0'

target 'TestFrameworkB_Example' do
  pod 'TestFrameworkB', :path => '../'

  target 'TestFrameworkB_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
